version: "3.3"

services:
  backend:
    build:
      context: ./backend
    secrets:
      - db-password
    depends_on:
      - mariadb

  mariadb:
    container_name: ${APP_NAME}-db
    image: "mariadb:${MARIADB_VERSION}"
    restart: 'always'
    volumes: 
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"

  proxy:
    build: proxy
    ports:
      - 80:80
    depends_on: 
      - backend

volumes:
  db-data:

secrets:
  db-password:
    file: mariadb/password.txt
