version: "3.3"

services:
  backend:
    container_name: ${APP_NAME}-backend
    build:
      context: ./backend
    secrets:
      - db-password
    env_file:
      - ./.env
    depends_on:
      - mariadb
    ports:
      - 8080:8080

  mariadb:
    container_name: ${APP_NAME}-db
    image: "mariadb:${MARIADB_VERSION}"
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent", "--password", "${MYSQL_ROOT_PASSWORD}"]
    volumes: 
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_INITDB_SKIP_TZINFO: 1
    ports:
      - 3306:3306

  proxy:
    container_name: ${APP_NAME}-nginx
    build:
      context: ./proxy
    ports:
      - 80:80
    depends_on: 
      - backend

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt
