version: '3'

services:
  db:
    image: mariadb:10.6
    container_name: ${APP_NAME}-db
    restart: always
    networks:
      - locanet
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_DATABASE=${DB_NAME}"   
      - "MYSQL_INITDB_SKIP_TZINFO=1"
    ports:
      - "3306:3306"
    expose:
      - 3306

  api:
    build:
      context: ./backend/
    container_name: ${APP_NAME}-api
    ports:
      - "8000:8000"
    volumes:
      - "./backend/:/app"
    depends_on:
      - db
    links:
      - "db:database"
    networks:
      - locanet
    env_file: .env
    entrypoint: ["/app/wait-for.sh", "db:3306", "--"]
    command: ["CompileDaemon", "--build", "go build main.go", "--command", "./main"]

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: ${APP_NAME}-phpmyadmin
  #   links:
  #     - db
  #   environment:
  #     PMA_HOST: db
  #     PMA_PORT: 3306
  #     # PMA_ARBITRARY: 1
  #     MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
  #   restart: always
  #   ports:
  #     - 5599:80
  #   networks: 
  #     - locanet

  web:
    container_name: ${APP_NAME}-frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - "./frontend/:/app"
      - '/frontend/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    networks: 
      - locanet

networks:
    locanet:
        driver: bridge